feat: End-to-end gravity test. (#2024)
- Gravity agent tasting framework using configurable commands.
- Test passes but protocol hangs.
- Sleep required to allow spaces to complete initialization before
clients shutdown.


```
Executing mocha...
Running setup script.
Setup script finished in 71 ms.


  Agent
    ✓ tests two agents (248ms)


  1 passing (360ms)

packages/core/mesh/network-manager/src/swarm/swarm.ts:211 WARN ignored for destroyed swarm { peerId: PublicKey(5824..3147), topic: PublicKey(541d..2cb6) }
packages/core/mesh/network-manager/src/swarm/swarm.ts:211 WARN ignored for destroyed swarm { peerId: PublicKey(5824..3147), topic: PublicKey(541d..2cb6) }
packages/core/mesh/network-manager/src/network-manager.ts:179 WARN swarm not open { topic: PublicKey(541d..2cb6) }
packages/core/mesh/mesh-protocol/src/protocol.ts:146 ERROR Error: ETIMEDOUT
    at ProtocolStream.<anonymous> (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/hypercore-protocol@8.0.7/node_modules/hypercore-protocol/index.js:363:51)
    at Object.onceWrapper (node:events:627:28)
    at ProtocolStream.emit (node:events:513:28)
    at Timeout.call (/Users/burdon/Code/dxos/dxos/node_modules/.pnpm/timeout-refresh@1.0.3/node_modules/timeout-refresh/refresh.js:25:18)
    at listOnTimeout (node:internal/timers:566:11)
    at processTimers (node:internal/timers:507:7)
```

Co-authored-by: Zhenya <zhenya@zhenya.co>